### ISSUE TITLE
Comments on review

### ISSUE THREAD

**Issue by hoc3426** [michamos/RPP-online-hep-info#4]
1. Add IN2P3 to the INSPIRE section
2. OSTI has replaced "SciTech Connect" with OSTI.GOV
  https://www.osti.gov/about
3. The orange boxes have some information on similar services offered by other parties for each category. This is particularly the case for People:
  https://inspirehep.net/collection/HepNames
(don't know if it's worth duplicating this or not, might make it look less INSPIREsy).
4. In the Jobs section
  https://academicjobsonline.org/ajo
might be a useful addition. It's scope is all of academia but it might be helpful to people working in edge fields or those wanting to get into something new (but still stay in academia).
5. In the software section, Pythia would be a good inclusion
  http://home.thep.lu.se/~torbjorn/Pythia.html
6. The data preservation site mentioned
  http://recast.cern.ch/
doesn't seem to go anywhere. Maybe ask Kyle what the latest is with this.
7. In the News section, the link for Fermilab should be
  https://news.fnal.gov/

Might be good to show this to the AB for input.

**Comment by michamos** [comment]
@hoc3426 Thanks a lot for your comments! I addressed most of them, except:

>     3\. The orange boxes have some information on similar services offered by other parties for each category. This is particularly the case for People:
>         https://inspirehep.net/collection/HepNames

I think it would be valuable to add ADS Astroperson (the others seem to specific or too far away from HEP), I've asked Alberto for more info about its status (still on ADS classic platform).

>     5\. In the software section, Pythia would be a good inclusion
>         http://home.thep.lu.se/~torbjorn/Pythia.html

It's part of the extended online version at https://library.web.cern.ch/particle_physics_information. I plan to put everything here and filter out some parts for the TeX version, but that will have to wait for later.

>     6\. The data preservation site mentioned
>         http://recast.cern.ch/
>         doesn't seem to go anywhere. Maybe ask Kyle what the latest is with this.

Yes, I've noticed it too. I've contacted Kyle for suggestions, but I'll point this out to him more specifically.
